[project]
name = "amazon-sales"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "boto3>=1.43.12",
    "nxd-data-product>=0.41.43",
    "pandas>=2.3.3",
    "snowflake-connector-python>=4.5.0",
]

[tool.uv.sources]
nxd-data-product = { index = "nxd" }

[[tool.uv.index]]
name = "nxd"
url = "https://registry.trynxd.com/index/"


[dependency-groups]
dev = [
    "python-dotenv>=1.2.2",
]
