# ruff: noqa: F403, F405
from nxd_models import *

# Input model — what we keep per Jira issue after parsing the API response.
# Fields beyond the free-text trio (`summary`, `description`, `comments`)
# are carried into the vector store as metadata.
jira_issue = (
    semantic_model(
        name="jira_issue",
        description="One Atlassian Jira issue retrieved from "
        "`/rest/api/3/search/jql`, filtered to project NXD. Free-text "
        "fields (`summary`, `description`, `comments`) are vectorised by "
        "the transform; the remaining fields ride along as metadata.",
    )
    .schema(
        {
            "id": (string(), "Jira issue id."),
            "key": (string(), "Jira issue key (e.g. `NXD-123`)."),
            "project": (string(), "Project key (always `NXD` for this product)."),
            "status": (string(), "Current workflow status name (e.g. `Open`, `In Progress`)."),
            "summary": (string(), "Issue summary / title — vectorised."),
            "description": (string(), "Issue description body — vectorised."),
            "comments": (
                string(),
                "All comments concatenated (newline-separated) — vectorised.",
            ),
            "created": (string(), "Issue creation timestamp (ISO 8601 string from Jira)."),
            "updated": (string(), "Last update timestamp (ISO 8601 string from Jira)."),
        }
    )
)


# MCP search tool models — request/response for `search_jira_issues`,
# exposed via the DP's RPC output port.
search_request = (
    semantic_model(
        name="search_request",
        description="Request for semantic search over the embedded Jira issues.",
    )
    .schema(
        {
            "query": (string(), "Free-text search query."),
            "top_k": (
                int64(),
                "Maximum number of chunks to return (default 5, max 25).",
            ),
        }
    )
)

search_response = (
    semantic_model(
        name="search_response",
        description="Semantic-search results over the embedded Jira issues.",
    )
    .schema(
        {
            "results": (
                string(),
                "JSON array of matches: content, issue_key, status, "
                "updated, similarity score.",
            ),
            "count": (int64(), "Number of matches returned."),
        }
    )
)


# Output model — mirrors the table shape used by
# `langchain_postgres.PGVectorStore`:
#
#   langchain_id       text          (UUID generated by langchain)
#   content            text
#   embedding          vector(384)   (declared via `vector_embeddings(384)`)
#   langchain_metadata text          (JSON-encoded metadata)
#
# The model name doubles as the physical table name (the pgvector driver
# provisions `CREATE TABLE IF NOT EXISTS <model-name>`), so it must match
# the table the transform writes to.
jira_issue_embeddings = (
    semantic_model(
        name="jira_issue_embeddings",
        description="One chunk of vectorised Jira free-text plus its "
        "metadata, written through `langchain_postgres.PGVectorStore`.",
    )
    .schema(
        {
            "langchain_id": (
                string(),
                "Stable UUID generated by langchain_postgres for the row.",
            ),
            "content": (
                string(),
                "The chunk of free text (≤512 chars) that was embedded.",
            ),
            "embedding": (
                vector_embeddings(384),
                "384-dim sentence embedding from `all-MiniLM-L6-v2`, "
                "stored as `vector(384)` in pgvector.",
            ),
            "langchain_metadata": (
                string(),
                "JSON-encoded metadata: issue `id`, `key`, `project`, "
                "`status`, `created`, `updated`.",
            ),
        }
    )
)
