# ruff: noqa: F403, F405
from nxd_models import *

# Input model — what we keep per Jira issue after parsing the API response.
# Fields beyond the free-text trio (`summary`, `description`, `comments`)
# are carried into the vector store as metadata.
jira_issue = (
    semantic_model(
        name="jira_issue",
        description="One Atlassian Jira issue retrieved from "
        "`/rest/api/3/search/jql`, filtered to project NXD. Free-text "
        "fields (`summary`, `description`, `comments`) are vectorised by "
        "the transform; the remaining fields ride along as metadata.",
    )
    .schema(
        {
            "id": (string(), "Jira issue id."),
            "key": (string(), "Jira issue key (e.g. `NXD-123`)."),
            "project": (string(), "Project key (always `NXD` for this product)."),
            "status": (string(), "Current workflow status name (e.g. `Open`, `In Progress`)."),
            "summary": (string(), "Issue summary / title — vectorised."),
            "description": (string(), "Issue description body — vectorised."),
            "comments": (
                string(),
                "All comments concatenated (newline-separated) — vectorised.",
            ),
            "created": (string(), "Issue creation timestamp (ISO 8601 string from Jira)."),
            "updated": (string(), "Last update timestamp (ISO 8601 string from Jira)."),
        }
    )
)


# Output model — mirrors the table shape created by
# `PGEngine.init_vectorstore_table(vector_size=384, ...)`:
#
#   langchain_id     uuid          PRIMARY KEY
#   content          text          NOT NULL
#   embedding        vector(384)   NOT NULL
#   langchain_metadata json
#
# `vector` and `json` are complex types — represented here as `string`
# per the skill's compatibility note (complex types in semantic models
# are not yet fully supported by NXD).
jira_issue_embedding = (
    semantic_model(
        name="jira_issue_embeddings",
        description="One chunk of vectorised Jira free-text plus its "
        "metadata. Table shape is owned by `langchain_postgres.PGEngine."
        "init_vectorstore_table` — the model mirrors that shape.",
    )
    .schema(
        {
            "langchain_id": (
                string(),
                "Stable UUID generated by langchain_postgres for the row.",
            ),
            "content": (
                string(),
                "The chunk of free text (≤512 chars) that was embedded.",
            ),
            "embedding": (
                string(),
                "384-dim sentence embedding from `all-MiniLM-L6-v2`. "
                "Stored as `vector(384)` in pgvector; surfaced here as a "
                "string until NXD semantic models add native vector support.",
            ),
            "langchain_metadata": (
                string(),
                "JSON-encoded metadata: issue `id`, `key`, `project`, "
                "`status`, `created`, `updated`. Stored as `json` in "
                "pgvector; surfaced as a string per the same note.",
            ),
        }
    )
)

jira_issue_embeddings = (
    semantic_model(
        name="jira_issue_embedding",
        description="One chunk of vectorised Jira free-text plus its "
                    "metadata. Table shape is owned by `langchain_postgres.PGEngine."
                    "init_vectorstore_table` — the model mirrors that shape.",
    )
    .schema(
        {
            "langchain_id": (
                string(),
                "Stable UUID generated by langchain_postgres for the row.",
            ),
            "content": (
                string(),
                "The chunk of free text (≤512 chars) that was embedded.",
            ),
            # "embedding": (
            #     string(),
            #     "384-dim sentence embedding from `all-MiniLM-L6-v2`. "
            #     "Stored as `vector(384)` in pgvector; surfaced here as a "
            #     "string until NXD semantic models add native vector support.",
            # ),
            "langchain_metadata": (
                string(),
                "JSON-encoded metadata: issue `id`, `key`, `project`, "
                "`status`, `created`, `updated`. Stored as `json` in "
                "pgvector; surfaced as a string per the same note.",
            ),
        }
    )
)