[project]
name = "jira-issues-embeddings"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "langchain-huggingface>=1.2.2",
    "langchain-postgres>=0.0.17",
    "langchain-text-splitters>=1.1.2",
    "nxd-data-product>=0.41.51",
    "nxd-drivers[rpc]>=0.41.51",
    "psycopg[binary]>=3.3.4",
    "requests>=2.34.2",
    "sentence-transformers>=5.5.1",
]

[tool.uv.sources]
nxd-data-product = { index = "nxd" }
nxd-drivers = { index = "nxd" }

[[tool.uv.index]]
name = "nxd"
url = "https://registry.trynxd.com/index/"

[dependency-groups]
dev = [
    "python-dotenv>=1.2.2",
]
