default_language_version:
  python: python3.11
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.12.1
    hooks:
      # Run the linter.
      - id: ruff-check
        types_or: [ python ]
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python ]
  - repo: local
    hooks:
      - id: check-spec-imports
        name: Check spec.py import limit
        entry: .pre-commit-hooks/check_spec_imports.py
        language: script
        files: spec\.py$
        pass_filenames: true
      - id: docs-sentence-case
        name: docs sentence case headings
        files: ^data_products/.*\.md$
        language: python
        entry: python .pre-commit-hooks/md_sentence_case.py
      - id: docs-link-check-internal
        name: docs link check internal md links only
        files: ^data_products/.*\.md$
        language: python
        entry: python .pre-commit-hooks/md_link_check.py
        pass_filenames: false
      - id: docs-link-check-external
        name: docs link check external links
        files: ^data_products/.*\.md$
        language: python
        entry: python .pre-commit-hooks/md_link_check.py
        args: [--check-external-links]