# ruff: noqa: F403, F405
from nxd_models import *

# Input model: generated by rate source (timestamp + monotonic value)
rate_model = (
    semantic_model("rate_model")
    .description("sample input model that generates monotonically increasing numbers")
    .schema(
        {
            "timestamp": (
                timestamp(unit=DurationUnit.Milliseconds, timezone=None),
                "Time of record creation",
            ),
            "value": (number(), "Monotonically increasing value"),
        }
    )
)

# Output model: rate model with added message field
output_model = (
    semantic_model("output_model")
    .description("sample input model that generates monotonically increasing numbers")
    .schema(
        {
            "timestamp": (
                timestamp(unit=DurationUnit.Milliseconds, timezone=None),
                "Time of record creation",
            ),
            "value": (number(), "Monotonically increasing value"),
            "message": (
                string(),
                "Sample records showing how we can add a string field",
            ),
        }
    )
)
