import logging
from io import BytesIO

import numpy as np
import pandas as pd
import pyarrow as pa
import tiktoken
from docling.datamodel.base_models import InputFormat
from docling.datamodel.pipeline_options import PdfPipelineOptions
from docling.document_converter import DocumentConverter
from docling.document_converter import PdfFormatOption
from docling_core.transforms.chunker.hybrid_chunker import HybridChunker
from docling_core.transforms.chunker.tokenizer.openai import OpenAITokenizer
from docling_core.types.io import DocumentStream
from langchain.docstore.document import Document
from langchain_docling.loader import DoclingLoader
from langchain_pinecone import PineconeEmbeddings
from langchain_pinecone import PineconeVectorStore
from nxd.data_product.context import AzureDataLakeStorage
from nxd.data_product.context import DatabricksWrite
from nxd.data_product.context import PineconeOutput
from pinecone.core.openapi.inference.model.embeddings_list import EmbeddingsList
from pyspark.sql import SparkSession
from tenacity import retry
from tenacity import stop_after_attempt
from tenacity import wait_fixed
from utils import adls_to_bytesio
from utils import adls_to_parquet
from utils import documents_to_json_to_adls
from utils import pandas_to_databricks
from utils import parquet_to_adls

_logger = logging.getLogger("transform.main")
_logger.setLevel(logging.INFO)

# Create tokenizer and chunker once globally to avoid recreation overhead
_TOKENIZER = OpenAITokenizer(
    tokenizer=tiktoken.encoding_for_model("gpt-4o-mini"),
    max_tokens=2048,  # llama-text-embed-v2 max input tokens
)
_CHUNKER = HybridChunker(tokenizer=_TOKENIZER)


def _retrieve_and_prepare_document(
    stream: BytesIO,
    filename: str,
    metadata: dict,
    converter: DocumentConverter,
) -> list[Document]:
    document_stream = DocumentStream(
        name=metadata["path"],
        stream=stream,
    )

    loader = DoclingLoader(
        file_path=[document_stream],  # type: ignore
        converter=converter,
        chunker=_CHUNKER,
    )

    documents = loader.load()

    # metadata enrichment
    for d in documents:
        # remove docling metadata, it contains lots of nested information
        #   not currently compatible with Pinecones's metadata field
        d.metadata.pop("dl_meta", None)

        d.metadata.update(
            metadata
            | {
                # ensure data type compatability
                "source": filename,  # overwrite source value generated by Docling, otherwise the bytes type document_stream.stream, will be used.
                "date": metadata["date"].isoformat(),
                "companies": [c["symbol_display"] for c in metadata["companies"]],  # lists are limited to strings only
            }
        )

    return documents


def _pinecone_documents_transformation(
    market_announcements: AzureDataLakeStorage,
    pinecone: PineconeOutput,
    adls: AzureDataLakeStorage,
) -> None:
    # announcements dataset contains adls paths and metadata for asx annoucement pdfs
    announcements = adls_to_parquet(
        context=market_announcements,
        file_path=market_announcements.model_paths["announcements"].path,
    )

    announcements = announcements.select(
        [
            "path",
            "symbol",
            "annoucement_types",
            "companies",
            "date",
            "headline",
            "document_key",
        ]
    ).to_pylist()

    pipeline_options = PdfPipelineOptions(
        # basic text and table structure extraction only
        do_ocr=False,
        do_table_structure=True,
        generate_page_images=False,
        generate_picture_images=False,
    )
    converter = DocumentConverter(
        allowed_formats=[InputFormat.PDF],
        format_options={InputFormat.PDF: PdfFormatOption(pipeline_options=pipeline_options)},
    )

    @retry(stop=stop_after_attempt(5), wait=wait_fixed(60))
    def _embed_texts(self, texts: list[str], model: str, parameters: dict) -> EmbeddingsList:
        return self._client.inference.embed(model=model, inputs=texts, parameters=parameters)

    # monkey patch to enforce backoff
    PineconeEmbeddings._embed_texts = _embed_texts

    embeddings = PineconeEmbeddings(
        model="llama-text-embed-v2",
        api_key=pinecone.password,  # type: ignore
    )

    vectorstore = PineconeVectorStore(
        # index_name=pinecone.index,
        index_name="finance-documents-pilot",  # indexes set within manifest.yaml are not respected and will always default to the data product name
        namespace=pinecone.namespace,
        pinecone_api_key=pinecone.password,
        embedding=embeddings,
    )

    for announcement in announcements:
        path = announcement.get("path")
        document_key = announcement.get("document_key")
        if path is None or document_key is None:
            raise ValueError(f"Neither 'path' or 'document_key' can be None - {announcement}")

        _logger.info(f"Processing file: {path} with document key: {document_key}")
        if (
            len(
                vectorstore.index.list_paginated(
                    namespace=pinecone.namespace,
                    prefix=document_key,
                    limit=1,
                ).vectors
            )
            > 0
        ):
            _logger.info(f" File: {path} has already been processed, skipping")
            continue

        file_stream = adls_to_bytesio(
            context=market_announcements,
            file_path=path,
        )

        documents = _retrieve_and_prepare_document(
            file_stream,
            filename=document_key,
            metadata=announcement,
            converter=converter,
        )
        _logger.info(f"File: {path} processed by Docling")

        # write
        documents_to_json_to_adls(
            documents=documents,
            file_path=f"{adls.model_paths['documents'].path}/{path}.json",
            context=adls,
        )

        vectorstore.add_documents(
            documents=documents,
            batch_size=64,
            id_prefix=document_key,
        )
        _logger.info(f"Documents from: {path} written to Pinecone")


def _adls_databricks_growth_transformation(
    spark: SparkSession,
    income_statements: AzureDataLakeStorage,
    stock_history: AzureDataLakeStorage,
    adls: AzureDataLakeStorage,
    nxd_databricks_storage: DatabricksWrite,
) -> None:
    statements = adls_to_parquet(
        context=income_statements,
        file_path=income_statements.model_paths["income_statements"].path,
    ).to_pandas()
    history = adls_to_parquet(
        context=stock_history,
        file_path=stock_history.model_paths["history"].path,
    ).to_pandas()

    # resample
    history = history.groupby(["symbol", pd.Grouper(key="date", freq="Y")])["close"].last().reset_index()
    history["annual_return"] = history.groupby("symbol")["close"].pct_change()

    statements = statements[statements["metric"].isin(["net_income", "total_revenue"])]
    statements = statements.pivot_table(index=["symbol", "date"], columns="metric", values="value").reset_index()
    # growth rates
    statements["revenue_growth"] = statements.groupby("symbol")["total_revenue"].pct_change()
    statements["net_income_growth"] = statements.groupby("symbol")["net_income"].pct_change()

    growth = pd.merge_asof(
        history.sort_values("date"),
        statements.sort_values("date"),
        by="symbol",
        on="date",
        direction="backward",
    )

    # replace inf and -inf with nan
    growth.replace([np.inf, -np.inf], np.nan, inplace=True)

    # write to databricks
    growth_pandas = growth.copy(deep=True)
    # force datetime
    growth_pandas["date"] = pd.to_datetime(growth_pandas["date"], utc=True)
    pandas_to_databricks(
        spark,
        nxd_databricks_storage,
        growth_pandas,
        "growth",
        {
            "symbol": "string",
            "date": "timestamp_ntz",
            "close": "double",
            "annual_return": "double",
            "net_income": "double",
            "total_revenue": "double",
            "revenue_growth": "double",
            "net_income_growth": "double",
        },
    )

    # write to adls
    growth = pa.Table.from_pandas(growth, preserve_index=False)
    parquet_to_adls(adls, growth, adls.model_paths["growth"].path)


def _adls_databricks_dividend_sustainability_transformation(
    spark: SparkSession,
    financial_statements: AzureDataLakeStorage,
    company_dividends: AzureDataLakeStorage,
    adls: AzureDataLakeStorage,
    nxd_databricks_storage: DatabricksWrite,
) -> None:
    cash_flows = adls_to_parquet(
        context=financial_statements,
        file_path=financial_statements.model_paths["cash_flows"].path,
    ).to_pandas()
    dividends = pd.read_json(
        adls_to_bytesio(
            context=company_dividends,
            file_path=company_dividends.model_paths["dividends"].path,
        ),
        lines=True,
    )

    # annual dividends per share by bank
    dividends_annual = (
        dividends.assign(year=pd.to_datetime(dividends["payment_date"]).dt.year)
        .groupby(["bank", "year"])["dividend_per_share"]
        .sum()
        .reset_index()
    )

    # operating cash flow per share equivalent
    ocf_annual = (
        cash_flows[
            # Macquarie lacks operating_cash_flow, so may need something else
            cash_flows["metric"] == "operating_cash_flow"
        ]
        .assign(year=pd.to_datetime(cash_flows["date"]).dt.year)
        .groupby(["symbol", "year"])["value"]
        .sum()
        .reset_index()
        .rename(columns={"symbol": "bank", "value": "operating_cash_flow_thousands"})
    )
    symbol_bank_mapping = {
        "ANZ.AX": "ANZ",
        "MQG.AX": "Macquarie",
        "WBC.AX": "Westpac",
    }
    ocf_annual["bank"] = ocf_annual["bank"].replace(symbol_bank_mapping)

    sustainability = pd.merge(dividends_annual, ocf_annual, on=["bank", "year"], how="inner")

    # flags and  metrics
    sustainability["dividend_yield_trend"] = sustainability.groupby("bank")["dividend_per_share"].pct_change()
    sustainability["ocf_trend"] = sustainability.groupby("bank")["operating_cash_flow_thousands"].pct_change()
    sustainability["dividend_growth_vs_ocf_growth"] = (
        sustainability["dividend_yield_trend"] - sustainability["ocf_trend"]
    )
    sustainability["sustainability_flag"] = np.where(
        sustainability["dividend_growth_vs_ocf_growth"] > 0.1,
        "GROWING FASTER THAN OCF",
        np.where(
            sustainability["dividend_growth_vs_ocf_growth"] > 0,
            "MODERATE GROWTH",
            "CONSERVATIVE GROWTH",
        ),
    )

    sustainability[
        [
            "bank",
            "year",
            "dividend_per_share",
            "operating_cash_flow_thousands",
            "dividend_yield_trend",
            "ocf_trend",
            "dividend_growth_vs_ocf_growth",
            "sustainability_flag",
        ]
    ]

    # replace inf and -inf with nan
    sustainability.replace([np.inf, -np.inf], np.nan, inplace=True)

    # write to databricks
    sustainability_pandas = sustainability.copy(deep=True)
    pandas_to_databricks(
        spark,
        nxd_databricks_storage,
        sustainability_pandas,
        "dividend_sustainability",
        {
            "bank": "string",
            "year": "int",
            "dividend_per_share": "decimal(4,2)",
            "operating_cash_flow_thousands": "double",
            "dividend_yield_trend": "double",
            "ocf_trend": "double",
            "dividend_growth_vs_ocf_growth": "double",
            "sustainability_flag": "string",
        },
    )

    # write to adls
    sustainability = pa.Table.from_pandas(sustainability, preserve_index=False)
    parquet_to_adls(adls, sustainability, adls.model_paths["dividend_sustainability"].path)


def transform(
    spark: SparkSession,
    market_announcements: AzureDataLakeStorage,
    income_statements: AzureDataLakeStorage,
    stock_history: AzureDataLakeStorage,
    financial_statements: AzureDataLakeStorage,
    company_dividends: AzureDataLakeStorage,
    aps_330_public_disclosures: AzureDataLakeStorage,
    # pinecone: PineconeOutput,
    adls: AzureDataLakeStorage,
    nxd_databricks_storage: DatabricksWrite,
) -> None:
    _logger.info("Starting au-competitor-analysis transformation...")

    # transform

    _adls_databricks_growth_transformation(
        spark,
        income_statements,
        stock_history,
        adls,
        nxd_databricks_storage,
    )

    _adls_databricks_dividend_sustainability_transformation(
        spark,
        financial_statements,
        company_dividends,
        adls,
        nxd_databricks_storage,
    )

    # _pinecone_documents_transformation(
    #     market_announcements,
    #     pinecone,
    #     adls,
    # )

    _logger.info("Transform completed successfully")
